name: Build APK

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Instalar EAS CLI globalmente
        run: npm install -g eas-cli

      - name: Build APK locally with EAS
        run: eas build -p android --profile preview --non-interactive --local --output=ImReadyHabits.apk
        env:
          EXPO_TOKEN: ${{ secrets.KALLI_BUILDER }}

      - name: Upload APK to release
        uses: softprops/action-gh-release@v2
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          files: ./ImReadyHabits.apk